"""Load harness: RPS and p95 against daari serve (issue #215).

Two named mixes on the same machine:

- **cache** — warm a small L0 set, then replay it concurrently
- **generate** — unique prompts, `X-Daari-No-Cache`, `max_tokens` capped so
  the run finishes

No vegeta/k6 dependency: asyncio + httpx. Skips cleanly without Ollama.
Writes `docs/developer/resources/benchmark-load.md`.

Run: python scripts/bench_load.py
"""

from __future__ import annotations

import argparse
import asyncio
import importlib.util
import os
import sys
import time
import uuid
from pathlib import Path
from typing import Any

import httpx

REPO = Path(__file__).resolve().parents[1]
DEFAULT_OUT = REPO / "docs" / "developer" / "resources" / "benchmark-load.md"

_spec = importlib.util.spec_from_file_location("bench_live", REPO / "scripts" / "bench_live.py")
bench_live = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(bench_live)

MIXES = ("cache", "generate")

# Short factual questions that stay on L3 and write L0. Nonsense tokens like
# "load-cache-warm" escalate to L4 (low confidence) and inflate warmup time.
CACHE_SEEDS = (
    "In one short sentence, what is a cache?",
    "In one short sentence, what is a database index?",
    "In one short sentence, what does HTTP status 404 mean?",
    "In one short sentence, what is a mutex?",
    "In one short sentence, what is RAM?",
    "In one short sentence, what is an API?",
    "In one short sentence, what is a process?",
    "In one short sentence, what is a TCP handshake?",
)


def replay_from_probes(seeds: list[str], hits: list[bool]) -> list[str]:
    """Keep only prompts whose post-warm probe was an L0 hit."""
    return [seed for seed, hit in zip(seeds, hits, strict=True) if hit]


def summarize(
    samples: list[float],
    *,
    errors: int,
    elapsed_s: float,
    concurrency: int,
    cache_hits: int = 0,
) -> dict[str, Any]:
    total = len(samples) + errors
    return {
        "count": len(samples),
        "errors": errors,
        "error_rate": (errors / total) if total else 1.0,
        "p50_ms": bench_live.percentile(samples, 50) if samples else 0.0,
        "p95_ms": bench_live.percentile(samples, 95) if samples else 0.0,
        "rps": (len(samples) / elapsed_s) if elapsed_s > 0 else 0.0,
        "concurrency": concurrency,
        "cache_hit_rate": (cache_hits / len(samples)) if samples else 0.0,
    }


def render_markdown(report: dict[str, Any]) -> str:
    lines = [
        "# Benchmark: load",
        "",
        "Generated by `python scripts/bench_load.py` against a hermetic `daari serve`",
        "and real Ollama. Two mixes: a warmed L0 replay (cache) and unique",
        "no-cache generations with `max_tokens` capped (generate). Reproduce:",
        "[guide](../guides/observability/live-benchmark.md#load).",
        "",
        f"- **Date:** {report['date']}",
        f"- **Commit:** `{report['commit']}`",
        f"- **Hardware:** {report['hardware']}",
        f"- **Ollama:** {report['ollama_version']}",
        "",
        "## Mixes",
        "",
        "| Mix | Requests | Concurrency | RPS | p50 ms | p95 ms | L0 hit | Errors |",
        "|-----|----------|-------------|-----|--------|--------|--------|--------|",
    ]
    for name in MIXES:
        mix = report["mixes"][name]
        lines.append(
            f"| {name} | {mix['count']} | {mix['concurrency']} | {mix['rps']:.1f} "
            f"| {mix['p50_ms']:.0f} | {mix['p95_ms']:.0f} "
            f"| {mix.get('cache_hit_rate', 0.0):.0%} | {mix['errors']} |"
        )
    lines += [
        "",
        "Cache RPS is the replay phase only (warm-up is excluded). The L0 hit",
        "column is `daari_meta.cache_hit` on those replay requests. Generate",
        "requests carry `X-Daari-No-Cache` and a small `max_tokens` so the run",
        "is a latency/throughput sample, not a quality eval.",
        "",
    ]
    return "\n".join(lines)


async def _chat(
    client: httpx.AsyncClient,
    prompt: str,
    *,
    no_cache: bool = False,
    max_tokens: int | None = None,
) -> tuple[bool, float, bool]:
    payload: dict[str, Any] = {
        "model": "daari",
        "messages": [{"role": "user", "content": prompt}],
    }
    if max_tokens is not None:
        payload["max_tokens"] = max_tokens
    headers = {}
    if no_cache:
        headers["X-Daari-No-Cache"] = "true"
    started = time.perf_counter()
    try:
        response = await client.post("/v1/chat/completions", json=payload, headers=headers)
        ms = (time.perf_counter() - started) * 1000
        meta = (response.json() or {}).get("daari_meta") or {}
        return response.status_code == 200, ms, bool(meta.get("cache_hit"))
    except Exception:
        return False, (time.perf_counter() - started) * 1000, False


async def _bounded(
    client: httpx.AsyncClient,
    prompts: list[str],
    concurrency: int,
    *,
    no_cache: bool,
    max_tokens: int | None,
) -> tuple[list[float], int, int, float]:
    sem = asyncio.Semaphore(concurrency)
    samples: list[float] = []
    errors = 0
    cache_hits = 0

    async def one(prompt: str) -> None:
        nonlocal errors, cache_hits
        async with sem:
            ok, ms, hit = await _chat(client, prompt, no_cache=no_cache, max_tokens=max_tokens)
            if ok:
                samples.append(ms)
                if hit:
                    cache_hits += 1
            else:
                errors += 1

    started = time.perf_counter()
    await asyncio.gather(*(one(prompt) for prompt in prompts))
    return samples, errors, cache_hits, time.perf_counter() - started


async def run_cache_mix(
    client: httpx.AsyncClient, *, warm: int, requests: int, concurrency: int
) -> dict[str, Any]:
    seeds = [CACHE_SEEDS[i % len(CACHE_SEEDS)] for i in range(warm)]
    probes: list[bool] = []
    for prompt in seeds:
        ok, _, _ = await _chat(client, prompt)
        if not ok:
            return summarize([], errors=1, elapsed_s=0.0, concurrency=concurrency)
        probe_ok, _, hit = await _chat(client, prompt)
        if not probe_ok:
            return summarize([], errors=1, elapsed_s=0.0, concurrency=concurrency)
        probes.append(hit)
    confirmed = replay_from_probes(seeds, probes)
    if not confirmed:
        return summarize([], errors=warm, elapsed_s=0.0, concurrency=concurrency)
    replay = [confirmed[i % len(confirmed)] for i in range(requests)]
    samples, errors, cache_hits, elapsed = await _bounded(
        client, replay, concurrency, no_cache=False, max_tokens=None
    )
    return summarize(
        samples, errors=errors, elapsed_s=elapsed, concurrency=concurrency, cache_hits=cache_hits
    )


async def run_generate_mix(
    client: httpx.AsyncClient, *, requests: int, concurrency: int, max_tokens: int
) -> dict[str, Any]:
    prompts = [f"Say hi once. token={uuid.uuid4().hex}" for _ in range(requests)]
    samples, errors, cache_hits, elapsed = await _bounded(
        client, prompts, concurrency, no_cache=True, max_tokens=max_tokens
    )
    return summarize(
        samples, errors=errors, elapsed_s=elapsed, concurrency=concurrency, cache_hits=cache_hits
    )


async def run_all(
    daemon_url: str,
    timeout: float,
    *,
    cache_warm: int,
    cache_requests: int,
    cache_concurrency: int,
    generate_requests: int,
    generate_concurrency: int,
    max_tokens: int,
) -> dict[str, dict[str, Any]]:
    headers = {
        "X-Daari-Meta": "true",
        "X-Daari-No-Frontier": "true",
        "X-Daari-Client-Id": "bench-load",
    }
    async with httpx.AsyncClient(base_url=daemon_url, headers=headers, timeout=timeout) as client:
        cache = await run_cache_mix(
            client, warm=cache_warm, requests=cache_requests, concurrency=cache_concurrency
        )
        generate = await run_generate_mix(
            client,
            requests=generate_requests,
            concurrency=generate_concurrency,
            max_tokens=max_tokens,
        )
    return {"cache": cache, "generate": generate}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ollama", default=os.environ.get("OLLAMA_HOST", "http://127.0.0.1:11434"))
    parser.add_argument("--daemon", default=None)
    parser.add_argument("--out", default=str(DEFAULT_OUT))
    parser.add_argument("--timeout", type=float, default=180.0)
    parser.add_argument("--cache-warm", type=int, default=8)
    parser.add_argument("--cache-requests", type=int, default=200)
    parser.add_argument("--cache-concurrency", type=int, default=16)
    parser.add_argument("--generate-requests", type=int, default=16)
    parser.add_argument("--generate-concurrency", type=int, default=2)
    parser.add_argument("--max-tokens", type=int, default=8)
    parser.add_argument("--no-write", action="store_true")
    args = parser.parse_args(argv)

    try:
        ollama_version = httpx.get(f"{args.ollama}/api/version", timeout=5).json()["version"]
    except Exception as exc:
        print(f"SKIP: Ollama unreachable at {args.ollama} ({exc})")
        return 0

    daemon: bench_live.HermeticDaemon | None = None
    if args.daemon:
        try:
            assert httpx.get(f"{args.daemon}/health", timeout=5).status_code == 200
        except Exception as exc:
            print(f"SKIP: daemon unreachable at {args.daemon} ({exc})")
            return 0
        daemon_url = args.daemon
    else:
        daemon = bench_live.HermeticDaemon(args.ollama)
        if not daemon.wait_ready():
            daemon.stop()
            print("ERROR: hermetic daari serve failed to start")
            return 1
        daemon_url = daemon.url

    try:
        print("mix cache ...", flush=True)
        mixes = asyncio.run(
            run_all(
                daemon_url,
                args.timeout,
                cache_warm=args.cache_warm,
                cache_requests=args.cache_requests,
                cache_concurrency=args.cache_concurrency,
                generate_requests=args.generate_requests,
                generate_concurrency=args.generate_concurrency,
                max_tokens=args.max_tokens,
            )
        )
        print(
            f"  cache {mixes['cache']['rps']:.1f} rps p95={mixes['cache']['p95_ms']:.0f}ms "
            f"l0={mixes['cache']['cache_hit_rate']:.0%}",
            flush=True,
        )
        print(
            f"  generate {mixes['generate']['rps']:.1f} rps p95={mixes['generate']['p95_ms']:.0f}ms",
            flush=True,
        )
    finally:
        if daemon is not None:
            daemon.stop()

    report = {
        "date": time.strftime("%Y-%m-%d"),
        "commit": bench_live.git_commit(),
        "hardware": bench_live.hardware_summary(),
        "ollama_version": ollama_version,
        "mixes": mixes,
    }
    text = render_markdown(report)
    print(text)
    if not args.no_write:
        Path(args.out).write_text(text)
        print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
