apiVersion: v1
kind: Service
metadata:
  name: {{ include "daari.fullname" . }}
  labels:
    app.kubernetes.io/name: daari
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: daari
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
